/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package lib.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Student extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6102652688157138049L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Student\",\"namespace\":\"lib.avro\",\"fields\":[{\"name\":\"index\",\"type\":\"string\"},{\"name\":\"firstname\",\"type\":\"string\"},{\"name\":\"lastname\",\"type\":\"string\"},{\"name\":\"faculty\",\"type\":\"string\"},{\"name\":\"espb\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Student> ENCODER =
      new BinaryMessageEncoder<Student>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Student> DECODER =
      new BinaryMessageDecoder<Student>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Student> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Student> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Student> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Student>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Student to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Student from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Student instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Student fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence index;
  private java.lang.CharSequence firstname;
  private java.lang.CharSequence lastname;
  private java.lang.CharSequence faculty;
  private int espb;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Student() {}

  /**
   * All-args constructor.
   * @param index The new value for index
   * @param firstname The new value for firstname
   * @param lastname The new value for lastname
   * @param faculty The new value for faculty
   * @param espb The new value for espb
   */
  public Student(java.lang.CharSequence index, java.lang.CharSequence firstname, java.lang.CharSequence lastname, java.lang.CharSequence faculty, java.lang.Integer espb) {
    this.index = index;
    this.firstname = firstname;
    this.lastname = lastname;
    this.faculty = faculty;
    this.espb = espb;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return index;
    case 1: return firstname;
    case 2: return lastname;
    case 3: return faculty;
    case 4: return espb;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: index = (java.lang.CharSequence)value$; break;
    case 1: firstname = (java.lang.CharSequence)value$; break;
    case 2: lastname = (java.lang.CharSequence)value$; break;
    case 3: faculty = (java.lang.CharSequence)value$; break;
    case 4: espb = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'index' field.
   * @return The value of the 'index' field.
   */
  public java.lang.CharSequence getIndex() {
    return index;
  }


  /**
   * Sets the value of the 'index' field.
   * @param value the value to set.
   */
  public void setIndex(java.lang.CharSequence value) {
    this.index = value;
  }

  /**
   * Gets the value of the 'firstname' field.
   * @return The value of the 'firstname' field.
   */
  public java.lang.CharSequence getFirstname() {
    return firstname;
  }


  /**
   * Sets the value of the 'firstname' field.
   * @param value the value to set.
   */
  public void setFirstname(java.lang.CharSequence value) {
    this.firstname = value;
  }

  /**
   * Gets the value of the 'lastname' field.
   * @return The value of the 'lastname' field.
   */
  public java.lang.CharSequence getLastname() {
    return lastname;
  }


  /**
   * Sets the value of the 'lastname' field.
   * @param value the value to set.
   */
  public void setLastname(java.lang.CharSequence value) {
    this.lastname = value;
  }

  /**
   * Gets the value of the 'faculty' field.
   * @return The value of the 'faculty' field.
   */
  public java.lang.CharSequence getFaculty() {
    return faculty;
  }


  /**
   * Sets the value of the 'faculty' field.
   * @param value the value to set.
   */
  public void setFaculty(java.lang.CharSequence value) {
    this.faculty = value;
  }

  /**
   * Gets the value of the 'espb' field.
   * @return The value of the 'espb' field.
   */
  public int getEspb() {
    return espb;
  }


  /**
   * Sets the value of the 'espb' field.
   * @param value the value to set.
   */
  public void setEspb(int value) {
    this.espb = value;
  }

  /**
   * Creates a new Student RecordBuilder.
   * @return A new Student RecordBuilder
   */
  public static lib.avro.Student.Builder newBuilder() {
    return new lib.avro.Student.Builder();
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Student RecordBuilder
   */
  public static lib.avro.Student.Builder newBuilder(lib.avro.Student.Builder other) {
    if (other == null) {
      return new lib.avro.Student.Builder();
    } else {
      return new lib.avro.Student.Builder(other);
    }
  }

  /**
   * Creates a new Student RecordBuilder by copying an existing Student instance.
   * @param other The existing instance to copy.
   * @return A new Student RecordBuilder
   */
  public static lib.avro.Student.Builder newBuilder(lib.avro.Student other) {
    if (other == null) {
      return new lib.avro.Student.Builder();
    } else {
      return new lib.avro.Student.Builder(other);
    }
  }

  /**
   * RecordBuilder for Student instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Student>
    implements org.apache.avro.data.RecordBuilder<Student> {

    private java.lang.CharSequence index;
    private java.lang.CharSequence firstname;
    private java.lang.CharSequence lastname;
    private java.lang.CharSequence faculty;
    private int espb;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(lib.avro.Student.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.firstname)) {
        this.firstname = data().deepCopy(fields()[1].schema(), other.firstname);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastname)) {
        this.lastname = data().deepCopy(fields()[2].schema(), other.lastname);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.faculty)) {
        this.faculty = data().deepCopy(fields()[3].schema(), other.faculty);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.espb)) {
        this.espb = data().deepCopy(fields()[4].schema(), other.espb);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Student instance
     * @param other The existing instance to copy.
     */
    private Builder(lib.avro.Student other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.index)) {
        this.index = data().deepCopy(fields()[0].schema(), other.index);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstname)) {
        this.firstname = data().deepCopy(fields()[1].schema(), other.firstname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastname)) {
        this.lastname = data().deepCopy(fields()[2].schema(), other.lastname);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.faculty)) {
        this.faculty = data().deepCopy(fields()[3].schema(), other.faculty);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.espb)) {
        this.espb = data().deepCopy(fields()[4].schema(), other.espb);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'index' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndex() {
      return index;
    }


    /**
      * Sets the value of the 'index' field.
      * @param value The value of 'index'.
      * @return This builder.
      */
    public lib.avro.Student.Builder setIndex(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.index = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'index' field has been set.
      * @return True if the 'index' field has been set, false otherwise.
      */
    public boolean hasIndex() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'index' field.
      * @return This builder.
      */
    public lib.avro.Student.Builder clearIndex() {
      index = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstname' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstname() {
      return firstname;
    }


    /**
      * Sets the value of the 'firstname' field.
      * @param value The value of 'firstname'.
      * @return This builder.
      */
    public lib.avro.Student.Builder setFirstname(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstname' field has been set.
      * @return True if the 'firstname' field has been set, false otherwise.
      */
    public boolean hasFirstname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstname' field.
      * @return This builder.
      */
    public lib.avro.Student.Builder clearFirstname() {
      firstname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastname' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastname() {
      return lastname;
    }


    /**
      * Sets the value of the 'lastname' field.
      * @param value The value of 'lastname'.
      * @return This builder.
      */
    public lib.avro.Student.Builder setLastname(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastname = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastname' field has been set.
      * @return True if the 'lastname' field has been set, false otherwise.
      */
    public boolean hasLastname() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastname' field.
      * @return This builder.
      */
    public lib.avro.Student.Builder clearLastname() {
      lastname = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'faculty' field.
      * @return The value.
      */
    public java.lang.CharSequence getFaculty() {
      return faculty;
    }


    /**
      * Sets the value of the 'faculty' field.
      * @param value The value of 'faculty'.
      * @return This builder.
      */
    public lib.avro.Student.Builder setFaculty(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.faculty = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'faculty' field has been set.
      * @return True if the 'faculty' field has been set, false otherwise.
      */
    public boolean hasFaculty() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'faculty' field.
      * @return This builder.
      */
    public lib.avro.Student.Builder clearFaculty() {
      faculty = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'espb' field.
      * @return The value.
      */
    public int getEspb() {
      return espb;
    }


    /**
      * Sets the value of the 'espb' field.
      * @param value The value of 'espb'.
      * @return This builder.
      */
    public lib.avro.Student.Builder setEspb(int value) {
      validate(fields()[4], value);
      this.espb = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'espb' field has been set.
      * @return True if the 'espb' field has been set, false otherwise.
      */
    public boolean hasEspb() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'espb' field.
      * @return This builder.
      */
    public lib.avro.Student.Builder clearEspb() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Student build() {
      try {
        Student record = new Student();
        record.index = fieldSetFlags()[0] ? this.index : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.firstname = fieldSetFlags()[1] ? this.firstname : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastname = fieldSetFlags()[2] ? this.lastname : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.faculty = fieldSetFlags()[3] ? this.faculty : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.espb = fieldSetFlags()[4] ? this.espb : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Student>
    WRITER$ = (org.apache.avro.io.DatumWriter<Student>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Student>
    READER$ = (org.apache.avro.io.DatumReader<Student>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.index);

    out.writeString(this.firstname);

    out.writeString(this.lastname);

    out.writeString(this.faculty);

    out.writeInt(this.espb);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.index = in.readString(this.index instanceof Utf8 ? (Utf8)this.index : null);

      this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);

      this.lastname = in.readString(this.lastname instanceof Utf8 ? (Utf8)this.lastname : null);

      this.faculty = in.readString(this.faculty instanceof Utf8 ? (Utf8)this.faculty : null);

      this.espb = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.index = in.readString(this.index instanceof Utf8 ? (Utf8)this.index : null);
          break;

        case 1:
          this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);
          break;

        case 2:
          this.lastname = in.readString(this.lastname instanceof Utf8 ? (Utf8)this.lastname : null);
          break;

        case 3:
          this.faculty = in.readString(this.faculty instanceof Utf8 ? (Utf8)this.faculty : null);
          break;

        case 4:
          this.espb = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










